package com.example.enums;

public enum AdminStep {
    STUDENT_FIRST_NAME_ASKING, STUDENT_FIRST_NAME_ASKED,
    STUDENT_LAST_NAME_ASKING, STUDENT_LAST_NAME_ASKED,
    STUDENT_PASSWORD_ASKING, STUDENT_PASSWORD_ASKED,
    STUDENT_CREATING_CANCELED, TRANSACTION_CANCELED,
    STUDENT_ID_ASKING, STUDENT_ID_ASKED,
    STUDENTS_OPENED, COURSES_OPENED,

    COURSES_NAME_ASKING, COURSES_NAME_ASKED,

    STUDENT_ADDING_TO_COURSE, STUDENT_ADDED_TO_COURSE,
    STUDENT_DELETING_FROM_COURSE, STUDENT_DELETED_FROM_COURSE,
    COURSE_OPENED,
    COURSE_DELETING, COURSE_DELETED
}
